### ISSUE TITLE
Day View Page

### ISSUE THREAD

**Issue by Polarts** [Polarts/feel-tracker#23]
# Prequisites:

#14, #16, #17 #19 and #22 should be finished first.

# Requirements:

- [ ] Add the `DayView` component under `src/routes/day`
- [ ] Implement a header that consists of month, year, and a link to change the view (currently inactive).
- [ ] Add the `DaySelector` component from #19.
- [ ] Implement a subheader with the text "Activities" and a link to "Filter" which triggers the `FilterModal` from #22.
- [ ] Map the activities from the `DayViewContext` to `ActivityCard` components from #17.

# Design:
