### ISSUE TITLE
FIX: Monkey patch for category modal

### ISSUE THREAD

**Issue by Polarts** [Polarts/feel-tracker#39]
# Description
A monkey patch has been applied to `CategoryBadge`: if no `onClick` callback is provided, a click will open the `CategoryModal` component by default.
Not sure if this is desired behavior, but programmatically it'd be more correct to have the modal open on-demand in the parent component rather than nested inside.

```ts
const handleOnClick = (event: MouseEvent | TouchEvent) => {
        event.stopPropagation();
        // TODO remove monkey patch
        onClick ? onClick() : setIsModalOpen(true);
    };
```

# Tasks
- [ ] Discuss the implication of removing it.
- [ ] Decide on a better solution (can write in a comment).
- [ ] Implement the solution.

**Comment by Ziv89** [comment]
I want to work on it.

**Comment by sufkis** [comment]
@Polarts What are we doing here?
I like the fact that clicking on a badge's colored body opens the Edit Category modal.
Claude's solution is to make the category unselect on click and I don't think that's what we want.
Let's discuss and decide what should be done here? before continue working on it
